### ISSUE TITLE
kinda ugly grey bar above "see past work" button

### ISSUE THREAD

**Issue by GeorgeWangnottaken** [hpvdt/website#41]
should remove

**Comment by savob** [comment]
Found the fix was quick @GeorgeWangnottaken, there was a class `project-box-lastcurrentproject` that was put on TITAN and not on the Streamliners, hence why the line came up in the wrong place.

There is in the CSS files a `:last-child` attribute for `project-box` classes that works for the last project (Snowbird), but doesn't work in this instance since all projects are in one parent section. If you perhaps split the projects into separate sections for past and present, then this `:last-child` would probably work as intended and we wouldn't need this `project-box-lastcurrentproject` class to maintain and juggle with future updates.

**Comment by GeorgeWangnottaken** [comment]
Oh yeah good idea about :last-child . Hopefully I'll get to use that CSS feature next time so the code is more legit
